// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfcWZQs9PNafLU4BmZ2Eg7MkpThqm2LR8',
    appId: '1:318693360051:web:2333b88f1e756fa9258bc6',
    messagingSenderId: '318693360051',
    projectId: 'shiharainu-app',
    authDomain: 'shiharainu-app.firebaseapp.com',
    storageBucket: 'shiharainu-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfcWZQs9PNafLU4BmZ2Eg7MkpThqm2LR8',
    appId: '1:318693360051:android:app_id_placeholder',
    messagingSenderId: '318693360051',
    projectId: 'shiharainu-app',
    storageBucket: 'shiharainu-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfcWZQs9PNafLU4BmZ2Eg7MkpThqm2LR8',
    appId: '1:318693360051:ios:app_id_placeholder',
    messagingSenderId: '318693360051',
    projectId: 'shiharainu-app',
    storageBucket: 'shiharainu-app.firebasestorage.app',
    iosBundleId: 'com.example.shiharainu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfcWZQs9PNafLU4BmZ2Eg7MkpThqm2LR8',
    appId: '1:318693360051:ios:app_id_placeholder',
    messagingSenderId: '318693360051',
    projectId: 'shiharainu-app',
    storageBucket: 'shiharainu-app.firebasestorage.app',
    iosBundleId: 'com.example.shiharainu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfcWZQs9PNafLU4BmZ2Eg7MkpThqm2LR8',
    appId: '1:318693360051:web:2333b88f1e756fa9258bc6',
    messagingSenderId: '318693360051',
    projectId: 'shiharainu-app',
    authDomain: 'shiharainu-app.firebaseapp.com',
    storageBucket: 'shiharainu-app.firebasestorage.app',
  );
}
